### Get all tasks
GET http://localhost:3000/tasks


### Get tasks with filter
### query params: status, search
GET http://localhost:3000/tasks?search=play

### Create a task
POST http://localhost:3000/tasks
content-type: application/json

{
    "title": "walk around the dog",
    "description": "go out with my dog and walk around"
}

### Find specific task by its id
GET http://localhost:3000/tasks/215e5a27-0bad-4362-a234-cc7c8e458203


### Delete a task by its id
DELETE http://localhost:3000/tasks/688bf642-7a7c-4b55-9c49-4a2511235324


### Update the status task given an id
PATCH http://localhost:3000/tasks/1c307f16-9771-4bf6-a0b3-25f32b598420/status
content-type: application/json

{
    "status": "OPEN"
}