### Get all tasks
GET http://localhost:3000/tasks


### Get tasks with filter
### query params: status, search
GET http://localhost:3000/tasks?search=wash&status=IN_PROGRESS

### Create a task
POST http://localhost:3000/tasks
content-type: application/json

{
    "title": "walk around the dog",
    "description": "go out with my dog and walk around"
}

### Find specific task by its id
GET http://localhost:3000/tasks/215e5a27-0bad-4362-a234-cc7c8e458203


### Delete a task by its id
DELETE http://localhost:3000/tasks/27164846-671e-42fb-a096-e4dabd06afdf


### Update the status task given an id
PATCH http://localhost:3000/tasks/1e7a8681-83ec-4a41-8dec-b0893dfc8855/status
content-type: application/json

{
    "status": "OPEN"
}