### Get all tasks
GET http://localhost:3000/tasks


### Get tasks with filter
### query params: status, search
GET http://localhost:3000/tasks?search=wALk


### Create a task
POST http://localhost:3000/tasks
content-type: application/json

{
    "title": "clean my room",
    "description": "clean an order my room"
}


### Find specific task by its id
GET http://localhost:3000/tasks/a3d41cf2-4052-44eb-909e-57dcfb16f414



### Delete a task by its id
DELETE http://localhost:3000/tasks/a3d41cf2-4052-44eb-909e-57dcfb16f414


### Update the status task given an id
PATCH http://localhost:3000/tasks/6ced135b-bb94-40ee-9ada-3b9925acb47c/status
content-type: application/json

{
    "status": "DONE"
}