### Sign Up
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "username": "antonio",
    "password": "12345678wW*"
}


### Sign In
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "username": "antonio",
    "password": "12345678wW*"
}